[workspace]
members = [
  "chat"
]


[workspace.package]
repository = "https://github.com/Inkvisto/InkManager.git"
license = "MIT"
edition = "2021"
rust-version = "1.82.0"

[workspace.dependencies]
async-std = "1.13"
futures = "0.3"

[workspace.lints]
