[package]
name = "inkmanager-chat"
version = "0.0.1"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-std.workspace = true
futures.workspace = true
# [dev-dependencies]

[lints]
workspace = true

[[bin]]
name = "chat"
path = "./bin.rs"

